Microsoft/YamUI

- package.json
setting up for initial publish
> first version bump

- .eslintrc.json
- config/backstop/config.js
- config/backstop/get-stories.js
- config/storybook/addons.js
- config/storybook/config.js
- config/storybook/webpack.config.js
- package.json
- postcss.config.js
- src/components/Avatar/avatar.test.tsx
- tslint.json
- yarn.lock
Addresses part of https://github.com/Microsoft/YamUI/issues/13
We'd need to do something equivalent with `tslint`... I may look into it when I have time.
> Add eslint-plugin-header to check copyright notices

- package.json
It'll also check for undeclared variables and other things.
> Enable type-checking on tslint

- src/components/Button/button.css
> never wrap contents of button

- package-lock.json
- package.json
> Release version 0.0.22

- LICENSE
The horizontal scrolling was bugging me.
> Wrap lines in LICENSE

- .travis.yml
- package-lock.json
- package.json
Releases a few breaking API changes:
- Buttons default to secondary instead of primary
- Clickable defaults to link styling with optional `unstyled` prop
- MessageBar no longer support `ariaLabel`
> Release version 1.0.0

- config/styleguide/config.js
- package.json
> Display version next to name

- config/styleguide/webpack.config.js
Useful when debugging examples.
> Enable sourcemaps

- package-lock.json
- package.json
> Release version 2.0.0

- .vscode/launch.json
> Add VSCode Jest Debug script

- package-lock.json
- package.json
> Release version 3.0.1

- package-lock.json
- package.json
- tsconfig.json
Revert es6 modules change, tag release 3.0.2
> CommonJS modules, release 3.0.2

- package-lock.json
- package.json
version bump for major release (HorizontalList was replaced with LayoutList)
> Release version 4.0.0

- src/components/SuggestionsList/SuggestionsList.test.tsx
- src/components/SuggestionsList/index.ts
Need to actually be able to import `components/SuggestionsList`
> SuggestionsList - create index file

- config/jest/config.json
- src/components/Dropdown/Dropdown.test.tsx
- src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Why ratchet down coverage when fixing it is straight forward
> Improve test coverage for Dropdown

- src/components/SuggestionsList/SuggestionsList.tsx
Pass through prop type def should match underlying Component's
> [SuggestionsList] props.target to match Callout

- src/components/SuggestionsList/SuggestionsList.test.tsx
- src/components/SuggestionsList/SuggestionsList.tsx
- src/components/SuggestionsList/__snapshots__/SuggestionsList.test.tsx.snap
> [SuggestionsList] Change mouseOut to mouseLeave

- package-lock.json
- package.json
Version bump from 4.0.0
Adds:-
* EngineeringGroup icon for communities
* Index file for `SuggestionsList`
* Fade in prop for `Avatar`
Changes:-
* `MediaObject` text now truncates
* `SuggestionsList` `mouseOver` -> `mouseLeave`
* Updates `SuggestionsList` `target` prop to match
> Release version 4.1.0

- package-lock.json
- package.json
- Add TextArea https://github.com/Microsoft/YamUI/pull/172
- Add topSpacing to Block https://github.com/Microsoft/YamUI/pull/189
> Release version 4.3.0

- package-lock.json
- package.json
* SuggestionsList will now always appear below target
> Release version 4.3.3

- package-lock.json
- package.json
This is to bring in a fix for the textfield suffix wrapping.
https://github.com/OfficeDev/office-ui-fabric-react/pull/3840
> Bump fabric to 5.45.1 and yamui to 4.3.4

- package-lock.json
- package.json
* Improvements to SuggestionsList
* Fixes Keyboard Navigation Listener to lazy instantiation
> Release version 4.4.1

- README.md
> docs(release)

- package-lock.json
- package.json
* Breaking changes to SuggestionsList; component no longer handling positioning
* Spinner alignment fix
> Release version 5.0.0

- README.md
> Update README.md to make version bumping more clear

- package-lock.json
- package.json
> Release version 5.2.0

- package-lock.json
- package.json
> Release version 5.3.0

- src/components/Avatar/Avatar.css
- src/components/Avatar/Avatar.tsx
- src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
Replacing `Persona` with lighter weigth `PersonaCoin`.
> Replace Persona with lighter weight PersonaCoin

- package-lock.json
- package.json
Includes:
https://github.com/Microsoft/YamUI/pull/286
https://github.com/Microsoft/YamUI/pull/289
https://github.com/Microsoft/YamUI/pull/291
> Release version 5.5.0

- src/components/Block/Block.css
> IE/Edge don't support overflow-wrap

- package-lock.json
- package.json
> Release 6.1.0

- src/components/BaseTextField/index.ts
Pipes ariaLabel through to Fabric's TextArea and TextField components
> Add ariaLabel to TextArea and TextField

- package-lock.json
- package.json
Includes:
https://github.com/Microsoft/YamUI/pull/300
https://github.com/Microsoft/YamUI/pull/301
https://github.com/Microsoft/YamUI/pull/302
> Release version 6.2.0

- .github/CODEOWNERS
> Add dannibal as Design owner, remove adrian and manuel

- package-lock.json
- package.json
> Release version 6.4.0

- src/components/NavigationLink/NavigationLink.test.tsx
- src/components/NavigationLink/NavigationLink.tsx
- src/components/NavigationLink/__snapshots__/NavigationLink.test.tsx.snap
> Adding ariaLabel to NavigationLink

- package-lock.json
- package.json
We're going to try and consume the new ES2015 modules from both clients.
> Release version 8.0.0

- package-lock.json
- package.json
- src/components/AsideSection/AsideSection.css
- src/components/AsideSection/AsideSection.styles.ts
- src/components/AsideSection/AsideSection.tsx
- src/components/AsideSection/__snapshots__/AsideSection.test.tsx.snap
> js styles for AsideSection

- package-lock.json
- package.json
> Release version 8.5.0

- package-lock.json
- src/components/AsideSection/AsideSection.styles.ts
- src/components/AsideSection/AsideSection.test.tsx
- src/components/AsideSection/AsideSection.tsx
- src/components/Button/Button.styles.ts
- src/components/Button/Button.test.tsx
A step towards making all components that use theme to be `customizable`.
In the next PR, I hope to do several/all components, just want to get eyes on this to make sure I'm setting up a good pattern.
> make AsideSection customizable

- package-lock.json
- package.json
8.6.0 introduces:
* SizeObserver component
* ResizeObserver polyfill
* Customizable SuggestionList, Picker, Text, Spinner, SidebarListItem, ProgressIndicator, PreviewCard, ModalDialog, MessageBar, Avatar and AsideSection
> Release version 8.6.0

- src/components/Customizer/Customizer.types.ts
It will cause consumers to pull all of Fabric.
> Avoid importing the root `office-ui-fabric-react`

- package-lock.json
- package.json
* Fixes import that would cause consumers to pull all of Fabric.
> Release version 8.7.0

- README.md
- package-lock.json
- package.json
Example size-limit failure: https://travis-ci.org/Microsoft/YamUI/builds/401033546
> add size limit for a demo component

- package-lock.json
- package.json
> Release version 8.9.0

- package-lock.json
- package.json
> Release version 8.11.0

- package-lock.json
- package.json
> Release version 8.12.0

- assets/icons/README.md
- assets/illustrations/README.md
> update Icon readme

- package-lock.json
- package.json
> Release version 8.14.1

- package-lock.json
- package.json
> Release version 8.15.0

- package-lock.json
- package.json
Includes:
https://github.com/Microsoft/YamUI/pull/500
https://github.com/Microsoft/YamUI/pull/501
> Release version 8.16.1

- package-lock.json
- package.json
> Release version 9.2.1

- package-lock.json
- package.json
> Release version 9.3.0

- package-lock.json
- package.json
Release version 9.4.0
Followed instructions at https://github.com/Microsoft/YamUI#releasing-a-new-version
> Release version 9.4.0

- package-lock.json
- package.json
> Release version 9.4.1

- package-lock.json
- package.json
- src/components/SuggestionsList/SuggestionsListItem.test.tsx
- src/components/SuggestionsList/SuggestionsListItem.tsx
- src/components/SuggestionsList/__snapshots__/SuggestionsListItem.test.tsx.snap
Previously this would result in a "Invalid Regular Expression" error
> handle parenthesis in the SuggestionListItem searchText

- src/components/NavigationLink/NavigationLink.test.tsx
- src/components/NavigationLink/NavigationLink.tsx
- src/components/NavigationLink/__snapshots__/NavigationLink.test.tsx.snap
Copy/paste from similar code in Clickable. Allows owning code to
set focus to the underlying link.
> feat(NavigationLink): add focusableRef to NavigationLink

- package-lock.json
- package.json
> Release version 10.1.0

- package-lock.json
- package.json
Update the YamUI version after adding the QuestionMessage newer icon: https://github.com/Microsoft/YamUI/pull/553
> Release version 10.1.1

- package-lock.json
- package.json
> Release version 10.2.0

- package-lock.json
- package.json
> Release version 10.2.1
