Microsoft/YamUI

src/util/fabric/theme.ts

This was removing Fabric's icon URLs from the theme config. Noticed when rendering a Dropdown component

Remove accidental blocking of Fabric icons

---

Dockerfile
package.json

The `sh -c serve docs` task is the parent of the `node_modules/.bin/serve docs` task. It's probably better to kill the child and let the parent terminate because of that. Also pkill may not find the process if it was started with a shell other than `sh`?
Also, we've seen that yarn v1.0.0 treats tasks that receive a SIGTERM as if they errored, which screws the way we run our visual tests. We're going to pin the version to v0.27.5 until we find a better solution.

Change pkill pattern, and pin yarn v0.27.5

---

.travis.yml

Travis is able to publish tagged releases automatically to npm. So releasing a new version of YamUI would only involve doing:
```
$ git checkout -b release-new-version
$ npm version patch "Release version %s"
$ git push
```
Once the pull request is reviewed and merged, Travis will publish to npm.

Setup Travis to auto-release to npm

---

src/css/base.css

CREDIT Brendan McKeon.
Additional baseline style override for button to remove border-radius added by Chrome 62 for MacOS: https://www.yammer.com/microsoft.com/#/Threads/show?threadId=970333082
(Soon mac users will have broken looking buttons like this example, unless we get this override in the baseline.)

Override border-radius for buttons

---

src/css/font-face.css

`font-display: optional` allows the browser to unblock initial page render, use the fallback until it can load the font, either on subsequent load, or by swapping it out if it loads quickly enough... More info and demo videos here: https://www.sitepoint.com/css-font-display-future-font-rendering-web/
No component/functional changes...

Add font-display optional to font-faces

---

src/css/font-face.css

Follow up on https://github.com/Microsoft/YamUI/pull/85, puts `swap` on `font-display` instead of `optional`.
No component/functional changes.

font-display: swap instead of optional

---

config/travis/build

`bin/sh` is not pointing to bash, so `set -o` fails.

Change script back to /bin/bash

---

src/components/Clickable/Clickable.tsx
src/components/Clickable/__snapshots__/Clickable.test.tsx.snap

Currently using Clickable inside of forms will cause a submission as there is no type set, defaulting to ‘submit’ (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)
*Describe the change you are making.*

[improvement] Update Clickable type to be button

---

config/styleguide/config.js

Import paths were not being generated properly after I moved the config file.
Here's what it was:
Here's what it should be:

Fix import paths in styleguide

---

config/styleguide/config.js
src/demos/ExampleWrapper/ExampleWrapper.tsx
src/demos/ExampleWrapper/index.ts

When our styleguide page gets loaded, all callouts render even though they're not in view, and it looks janky.
I'm proposing we don't render an example until it enters the viewport, by using `IntersectionObserver`.

Delay rendering of examples until they intersect the viewport

---

src/components/Image/Image.test.tsx
src/components/Image/Image.tsx
src/components/Image/__snapshots__/Image.test.tsx.snap
src/components/ProgressIndicator/ProgressIndicator.test.tsx
src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap

Defaults Image component's `shouldFadeIn` to false and surfaces the prop to allow it to fade in. Also updates ProgressIndicator to bring us back up to 100% test coverage.

Handle image fading

---

config/styleguide/context/action.js

The arrow function was ending up in the bundle, causing IE to choke.

Do not use ES6 features in action, as it doesn't get transpiled

---

src/components/Callout/Callout.css
src/components/Callout/Callout.md
src/components/Callout/Callout.tsx
src/components/Callout/index.ts
src/components/Hovercard/Hovercard.css
src/components/Hovercard/Hovercard.test.tsx
src/components/Hovercard/Hovercard.tsx

Couldn't find any reason to limit Fabric Callout's API as this is pretty much a utility component within YamUI, so I just exposed the Fabric component directly. There's still a little value in this wrapper since the CSS override is managed at this entrypoint instead of in Hovercard.

Extract Callout from Hovercard

---

config/yo/generator-component/app/templates/Component.test.tsx
src/components/Avatar/Avatar.test.tsx
src/components/Block/Block.test.tsx
src/components/Button/Button.test.tsx
src/components/Clickable/Clickable.test.tsx
src/components/Dropdown/Dropdown.test.tsx
src/components/FakeLink/FakeLink.test.tsx
src/components/FixedGrid/FixedGridColumn.test.tsx
src/components/FixedGrid/FixedGridRow.test.tsx
src/components/Heading/Heading.test.tsx
src/components/Heading/__snapshots__/Heading.test.tsx.snap
src/components/HorizontalList/HorizontalList.test.tsx
src/components/HorizontalList/HorizontalListItem.test.tsx
src/components/Hovercard/Hovercard.test.tsx
src/components/Hovercard/__snapshots__/Hovercard.test.tsx.snap
src/components/Icon/Icon.test.tsx
src/components/Image/Image.test.tsx
src/components/Image/__snapshots__/Image.test.tsx.snap
src/components/MediaObject/MediaObject.test.tsx
src/components/MessageBar/MessageBar.test.tsx
src/components/NavigationLink/NavigationLink.test.tsx
src/components/ProgressIndicator/ProgressIndicator.test.tsx
src/components/ScreenreaderText/ScreenreaderText.test.tsx
src/components/Spinner/Spinner.test.tsx
src/components/Text/Text.test.tsx
src/components/Text/__snapshots__/Text.test.tsx.snap

We should just be using snapshots to test the rendered output rather than flooding our files with unnecessary prop checks everywhere

[cleanup] Use snapshots to test rendered output

---

src/components/Avatar/Avatar.tsx

For highly dynamic content e.g. lists, drop-downs etc, Avatar images fading in every render is distracting, this adds a prop to pass through to Persona's imageShouldFadeIn

[avatar] Support disabling fade in

---

README.md
package.json
src/components/Tooltip/Tooltip.css
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap

Enables layering so Tooltip is rendered in a separate Fabric Layer with position:fixed instead of directly in its parent component with position:absolute. The downside is the Tooltip will disappear on scroll (same as Hovercard, and the existing Hovercard & Tooltip implementations on Yammer.com).
Also aliases "npm run start:dev" to "npm run start / npm start" and "npm run start:test" to "npm run jest:watch" to align with our other repos. Eventually we can delete the original "start:dev" and "start:test" aliases.

Allow tooltip to work in an overflow:hidden parent

---

package.json

This commit silten NPM warnings:
```sh
npm install
npm WARN ts-jest@20.0.6 requires a peer of jest@^20.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN yamui@4.2.0 No repository field.
up to date in 11.287s
```
to:
```sh
npm install
up to date in 11.198s
```
The PR is split into two separate comits:
- simple `package.json` update by `repository` tag being added
- udpate to `ts-jest` package version to be in sync with `jest` peer dependency 
The `repository` property update is simple and allows to use commands like `npm docs` or `npm repo` to switch to the project home.
The `ts-jest` is pushed as separate commit as it could also require `package-lock.json` update, which is not part of the PR as I have no idea on your …

Remove NPM warnings

---

src/components/Avatar/Avatar.tsx
src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
src/components/SuggestionsList/__snapshots__/SuggestionsListItem.test.tsx.snap

It appears a falsey ‘undefined’ value isn’t enough. Explicitly setting false is required

[Avatar] Fix default prop

---

src/components/Tooltip/Tooltip.css

Force no border for tooltip component.
Fabric is sometimes adding borders for tooltips.

Removed border for tooltips.

---

src/components/NavigationLink/NavigationLink.tsx
src/components/NavigationLink/__snapshots__/NavigationLink.test.tsx.snap

Additional security measure to make `window.opener=null`, so that the opened window doesn't have access to the parent window: https://mathiasbynens.github.io/rel-noopener/

Add noopener to links

---

src/components/BaseTextField/BaseTextField.css
src/components/BaseTextField/index.ts
src/components/TextArea/__snapshots__/TextArea.test.tsx.snap
src/components/TextField/__snapshots__/TextField.test.tsx.snap

`required` was triggering undesired browser behaviour. `aria-required` will still announce that the field is required without the undesired side effects. 
- added benefit is that I was also able to remove a style override that was hiding the asterisk that came along with `required`

Use aria-required attribute for Textfield instead of required

---

src/components/SuggestionsList/SuggestionsList.tsx
src/components/SuggestionsList/SuggestionsListItem.tsx
src/components/SuggestionsList/__snapshots__/SuggestionsList.test.tsx.snap
src/components/SuggestionsList/__snapshots__/SuggestionsListItem.test.tsx.snap
src/css/high-contrast.css
src/css/index.css

HC-specific rules added to:
* add border around the list
* use selection colors for the selected item
* avoid clipping on EDGE
Before:
After:

Add High Contrast rules for SuggestionsList

---

src/components/SuggestionsList/SuggestionsListItem.tsx
src/components/SuggestionsList/__snapshots__/SuggestionsListItem.test.tsx.snap

Speech input apps like Nuance's Dragon look for clicable candidates by scanning for
links, buttons, and similar interactive items. Adding role=button here allows a
user to say 'click <username>' to click one of the items in the list.

Add role=button to SuggestionListItem for compat with speech input

---

src/components/SuggestionsList/SuggestionsListItem.test.tsx
src/components/SuggestionsList/SuggestionsListItem.tsx

When clicking SuggestionListItems the mousedown event should be preventDefault’d so the focused item in the page doesn’t get blurred

fix(SuggestionListItem): Prevent SuggestionListItem from stealing focus

---

package-lock.json
package.json
src/components/Avatar/Avatar.css
src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
src/components/Button/__snapshots__/Button.test.tsx.snap
src/components/Dropdown/Dropdown.css
src/components/Fabric/__snapshots__/Fabric.test.tsx.snap
src/components/MenuButton/MenuButton.css
src/components/MenuButton/MenuButton.tsx
src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap
src/components/Spinner/__snapshots__/Spinner.test.tsx.snap
src/css/variables/borders.css
src/util/colors.ts
src/util/fabric/theme.ts

In preparation to allow custom description's on TextField.
https://github.com/OfficeDev/office-ui-fabric-react/pull/4588
1. Avatar - Persona initials changed line-height from 70px to 72px. Added overrided to fix.
https://github.com/OfficeDev/office-ui-fabric-react/pull/4382/files
2. MenuButton - Fabric IconButton refactor caused a change in css order. If you look at the commit history, my first fix was to use more specific selectors.  Then instead I passed the overrides in through the `styles` prop on IconButton.  I think this will generally be more maintainable, but don't feel great about the hard-coded color strings. Feedback?
3. Hovercard - .ms-Callout now has a 1px border, when we expected 0.  I've added an !important overrride here.
4. Various snapshot changes.

bump office-ui-fabric-react to 5.85.0

---

.gitignore
.prettierignore
config/jest/config.json
config/yo/generator-component/app/templates/Component.tsx
package-lock.json
package.json
src/css/variables/colors.css
src/util/accessibility/KeyboardNavigationEventListener.ts
tsconfig.json
tslint.json

- Fixes typo in .gitignore, to ignore just folders which begin with a dot
- Adds `.prettierignore` file i thought was already pushed to the repo
- Removes `collectCodeCoverageFrom` from Jest config to allow filtered test runs to only report numbers on the current dependency tree
- Fixes missing `public` keywords in component template
- Updates Jest dependencies
- Prettier formatting

A few linting and dependency chores

---

.eslintrc.json
config/jest/framework.js
package-lock.json
package.json
src/components/TextField/TextField.tsx
src/util/DebouncedOnChange/index.tsx

Our apps are on React 16 now, so upgrading YamUI with the goodness.
I was tempted to upgrade react-styleguidist as well, but i'll do that separately since it's not necessary yet. the newer version has some nice-to-haves for grouping components like we want.

Version bump React and friends, fix lint/type issues

---

src/components/Dropdown/Dropdown.test.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
src/components/TextArea/TextArea.test.tsx
src/components/TextArea/__snapshots__/TextArea.test.tsx.snap
src/components/TextField/TextField.test.tsx
src/components/TextField/__snapshots__/TextField.test.tsx.snap

Will need this for some use cases in yamjs where there's no
visual label.
Also updated snapshot test for TextField + TextArea to include ariaLabel.

Add ariaLabel to Dropdown

---

package-lock.json
package.json

Bumping version. Since we're changing the name of one of the props (componentRef -> focusableRef), it's a breaking change by semver rules.

Release version 7.0.0

---

package.json

since we're using `createRef` now

Bump react peer dependency to 16.3

---

package-lock.json
package.json
src/components/MenuButton/MenuButton.test.tsx
src/components/MenuButton/MenuButtonItem.test.tsx
src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap

Fabric used to set .is-focusVisible on root elements when keyboard
was in use. This broke in a recent version, but was restored in
5.89.0, so bumping to later than that.

Bump Fabric to recent to restore .is-focusVisible behavior

---

src/components/NavigationLink/NavigationLink.test.tsx
src/components/NavigationLink/NavigationLink.tsx
src/components/NavigationLink/__snapshots__/NavigationLink.test.tsx.snap

For use in left-nav and other situations where a link is styled in such a way
to indicate that it is the current item. Screenreaders will read out
'current page' when aria-current="page" is set.

Add aria-current support to NavigationLink

---

src/components/Block/Block.css
src/components/Block/Block.styles.ts
src/components/Block/Block.test.tsx
src/components/Block/Block.tsx
src/components/Block/__snapshots__/Block.test.tsx.snap
src/components/Clickable/Clickable.test.tsx
src/components/Clickable/Clickable.tsx
src/components/Clickable/__snapshots__/Clickable.test.tsx.snap
src/components/PreviewCard/PreviewCard.test.tsx
tslint.json

The primary goal was to remove the last of the css for the `Block` component. 
The rule is that a `Block` needs to be 100% width, when nested within a `Clickable` component.
To achieve this, I added a clickable Context Provider. 
This led to some challenges in our snapshot tests, which I've addressed to the best of my current ability, but I suspect there is room for improvement.

add clickable context

---

src/components/AsideSection/__snapshots__/AsideSection.test.tsx.snap
src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
src/components/Block/__snapshots__/Block.test.tsx.snap
src/components/Box/__snapshots__/Box.test.tsx.snap
src/components/Button/__snapshots__/Button.test.tsx.snap
src/components/Fabric/__snapshots__/Fabric.test.tsx.snap
src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
src/components/Text/__snapshots__/Text.test.tsx.snap
src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
src/util/colors.ts

This unblocks Spinner work where we need to use a Fabric util to add an alpha channel to a CSS color. `colors.ts` is the only changed file, the rest are updated snapshots

Convert yammer palette colors from hex to rgb

---

.github/CODEOWNERS

Plan is to flush the queue of PRs before we pause

Remove design codeowners for now

---

package-lock.json
package.json
src/components/Block/Block.styles.ts
src/components/Block/Block.test.tsx
src/components/Block/Block.tsx
src/components/Block/__snapshots__/Block.test.tsx.snap
src/components/Clickable/Clickable.styles.ts
src/components/Clickable/Clickable.tsx
src/components/Clickable/__snapshots__/Clickable.test.tsx.snap
src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
src/components/Text/Text.styles.ts
src/components/Text/Text.test.tsx
src/components/Text/Text.tsx
src/components/Text/__snapshots__/Text.test.tsx.snap

The use of the context api here was causing test failures in downstream dependencies, since it is not yet fully supported by enzyme. 
We were using context to achieve styles that were dependent on a specific nesting of components. 
Instead, we can use the `selectors` facility offered by merge-styles to achieve is, which I think is an overall better solution anyway.
fixes #411

Remove Context API - Use 'selectors' styles instead

---

config/styleguide/webpack.config.js
package-lock.json
package.json

Adds a polyfill for resize observer, which will be used in upcoming YamUI components (GridList and
ContainerQuery).

feat(resize observer): introduce polyfill

---

src/components/ChoiceGroup/ChoiceGroup.test.tsx
src/components/ChoiceGroup/ChoiceGroup.tsx
src/components/ChoiceGroup/__snapshots__/ChoiceGroup.test.tsx.snap

Fabric's ChoiceGroupOption is passed a labelId that it expects
the label to use around the content. We weren't aware of or using this,
so ended up with an overall ChoiceGroupOption that had an aria-label
property on the INPUT field that didn't end up pointing to any valid
element.
This change picks up and uses the labelId to fix this.

fix(a11y): use provided labelId in custom ChoiceGroup label

---

src/components/NavigationLink/NavigationLink.styles.ts
src/components/NavigationLink/__snapshots__/NavigationLink.test.tsx.snap
src/css/base.css

This reverts some of the change that I made in https://github.com/Microsoft/YamUI/pull/489
I learned that we depend on the anchor styling for the NavigationLink component in modern client.

fix link styles

---

README.md

It was previously linking to the assets/icons directory instead of
linking to the README.md within that directory. This has been fixed.

docs(readme): Fixing the asset instruction link.

---

src/components/AppContainer/AppContainer.styles.ts
src/components/AppContainer/AppContainer.tsx
src/components/AppContainer/__snapshots__/AppContainer.test.tsx.snap

Global box-sizing broke a config panel in SP. This moves the rule to AppContainer, and adds override styles for CalloutContent and Modal components since they render in a separate layer.

chore(styles): Scope global box-sizing rules to AppContainer and Layer components

---

Dockerfile

Was hitting random integrity and errors re missing .staging dir
with older npm, upgrading to latest seemd to get all working.

chore(docker): Get latest npm within docker image

---

src/components/PreviewCard/PreviewCard.types.ts

PreviewCard does not use any fallback icon if imageUrl is not present.
Issue reported here: https://github.com/Microsoft/YamUI/issues/530
That functionality was originally intended but not anymore.

Fix previewcard description to be consistent with the implementation.

---

src/components/ChoiceGroup/ChoiceGroup.styles.tsx
src/components/ChoiceGroup/__snapshots__/ChoiceGroup.test.tsx.snap

Modify indentation of ChoiceGroup component to more closely match polls on Yammer.com (https://yammer.visualstudio.com/frontend/_workitems/edit/19062)
Currently on Modern Client:
With this PR change:

refactor(YamUI): Modify indentation of ChoiceGroup component
